modLoader = "javafml"
loaderVersion = "[4,)"
license = "LGPL-3.0 License"

[[mods]]
modId = "mat"
version = "1.0.0"
displayName = "Minecraft Automated Testing"
authors = "Cait Sykes"
description = '''
Automated testing library for Minecraft GameTests.
'''

[[dependencies.mat]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mat]]
modId = "minecraft"
type = "required"
versionRange = "[1.21, 1.22)"
ordering = "NONE"
side = "BOTH"
